# Generated by Django 2.2.5 on 2019-10-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191005_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapper',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='scrapper',
            name='scrapped_by',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='scrapped',
            field=models.TextField(default=0),
        ),
    ]
