# Generated by Django 2.2.5 on 2019-10-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191005_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scrapped',
            field=models.IntegerField(default=0),
        ),
    ]
